[build]
builder = "dockerfile"

[[services]]
name = "concert-backend"
dockerfile = "./backend/Dockerfile"
context = "./backend"

[[services]]
name = "concert-frontend"
dockerfile = "./frontend/Dockerfile"
context = "./frontend"
