databases:
  - name: concert_db
    databaseName: concert_tickets
    user: concert_user
    plan: free

services:
  - type: web
    name: concert_api
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: concert_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile

  - type: web
    name: concert_frontend
    runtime: docker
    envVars:
      - key: REACT_APP_API_URL
        value: https://concert-api.onrender.com
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
